package com.exam;
// Generated May 16, 2019 9:55:08 PM by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private int id;
     private String name;
     private String image;

    public Image() {
    }

	
    public Image(int id) {
        this.id = id;
    }
    public Image(int id, String name, String image) {
       this.id = id;
       this.name = name;
       this.image = image;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


